[build]
  command = "sh scripts/build.sh"
  publish = "public"

[build.processing]
  skip_processing = false

[build.processing.html]
  pretty_urls = true

[[redirects]]
  from = "https://www.rodrigocantinhomaldonado.com/*"
  to   = "https://rodrigocantinhomaldonado.com/:splat"
  status = 301
  force  = true
