from datetime import date
from pathlib import Path
import html
import json
import re

ROOT = Path("public")
BASE = "https://rodrigocantinhomaldonado.com"
TODAY = date.today().isoformat()


def page(slug, title, description, intro, sections):
    return {"slug": slug, "title": title, "description": description,
            "h1": title.split(" | ")[0], "intro": intro, "sections": sections}


PAGES = [
    page("rodrigo-cantinho-maldonado-empresario", "Rodrigo Cantinho Maldonado empresário | Perfil oficial", "Perfil empresarial oficial de Rodrigo Cantinho Maldonado, com atuação em imóveis, hospitalidade, negócios e projetos digitais.", "Rodrigo Cantinho Maldonado desenvolve projetos que conectam ativos imobiliários, hospitalidade e presença digital. Sua atuação empresarial prioriza análise prática, organização operacional e comunicação clara para transformar oportunidades em projetos sustentáveis.", [("Visão empresarial", "Decisões são avaliadas por risco, custo, utilidade, liquidez e impacto de longo prazo."), ("Ativos imobiliários", "Imóveis são tratados como ativos que exigem diligência, manutenção, posicionamento e estratégia de saída."), ("Hospitalidade", "A experiência do hóspede depende de processos consistentes, atendimento e melhoria contínua."), ("Projetos digitais", "Canais próprios organizam informação, fortalecem marcas e reduzem dependência de plataformas terceiras.")]),
    page("como-avaliar-imovel-alto-padrao-rio", "Como avaliar imóvel de alto padrão no Rio de Janeiro", "Guia prático para avaliar preço, documentação, reforma, liquidez e custo total de um imóvel de alto padrão no Rio.", "Avaliar um imóvel de alto padrão no Rio de Janeiro exige ir além do preço por metro quadrado. Endereço, planta, estado real, documentação, condomínio, custo de reforma, financiamento e liquidez precisam ser comparados em um único cenário financeiro.", [("Preço comparável", "Use negócios e anúncios comparáveis, ajustando andar, vista, reforma, vagas, prédio e micro localização."), ("Custo total", "Some aquisição, impostos, escritura, reforma, condomínio, manutenção e custo do capital."), ("Diligência", "Matrícula, ônus, certidões, titularidade e regras condominiais devem ser verificados antes de pagamentos relevantes."), ("Saída e liquidez", "Considere o público comprador futuro e alternativas de uso, locação ou revenda.")]),
    page("comprar-cobertura-ipanema", "Comprar cobertura em Ipanema: guia de decisão", "Critérios financeiros, técnicos e jurídicos para analisar a compra de uma cobertura em Ipanema.", "Comprar uma cobertura em Ipanema pode reunir localização excepcional, privacidade e escassez, mas também concentra riscos específicos. Impermeabilização, elevador, áreas descobertas, documentação das ampliações e liquidez merecem diligência reforçada.", [("Cobertura regular", "Confira se terraços, piscinas, anexos e ampliações constam da planta, matrícula e cadastro municipal."), ("Inspeção técnica", "Avalie impermeabilização, fachadas, esquadrias, instalações, elevadores e sinais de infiltração."), ("Negociação", "Transforme obras necessárias, prazo de venda e risco documental em ajustes objetivos de preço e condições."), ("Cenário financeiro", "Compare entrada, CET, condomínio, IPTU, reforma e custo de oportunidade do capital.")]),
    page("vender-imovel-alto-padrao-ipanema", "Como vender imóvel de alto padrão em Ipanema", "Estratégia para preço, apresentação, divulgação e negociação de imóveis de alto padrão em Ipanema.", "Vender um imóvel de alto padrão em Ipanema exige coerência entre preço, apresentação e canais de divulgação. O objetivo não é apenas ampliar exposição, mas chegar ao comprador adequado com informações completas e controlar a negociação.", [("Preço defensável", "Defina uma faixa baseada em comparáveis, diferenciais reais, prazo e margem de negociação."), ("Apresentação", "Fotografia, vídeo, planta, documentação e descrição devem reduzir dúvidas e valorizar atributos verificáveis."), ("Distribuição", "Combine site próprio, rede profissional e canais selecionados, evitando anúncios conflitantes ou desatualizados."), ("Qualificação", "Antes da visita, alinhe interesse, capacidade financeira, prazo e condições relevantes.")]),
    page("gestao-airbnb-alto-padrao", "Gestão de Airbnb de alto padrão", "Como estruturar operação, custos, manutenção e experiência do hóspede em imóveis de temporada de alto padrão.", "A gestão de um Airbnb de alto padrão depende menos de promessas e mais de consistência. Preparação do imóvel, limpeza, enxoval, manutenção, comunicação, regras e resposta a incidentes precisam funcionar como uma operação integrada.", [("Padrão operacional", "Checklists claros para preparação, vistoria e fechamento reduzem falhas entre reservas."), ("Manutenção preventiva", "Inspeções programadas diminuem indisponibilidade, reparos emergenciais e impacto sobre avaliações."), ("Controle financeiro", "Acompanhe receita líquida, taxas, equipe, utilidades, reposições, manutenção e ociosidade."), ("Experiência e reputação", "Feedback recorrente deve virar prioridade operacional, investimento ou ajuste de comunicação.")]),
    page("custo-operacao-imovel-temporada", "Custos de um imóvel de temporada", "Guia dos custos diretos, indiretos e riscos financeiros na operação de imóveis de temporada.", "A diária anunciada não representa o resultado financeiro de um imóvel de temporada. Para medir rentabilidade real, é necessário consolidar custos fixos, despesas variáveis, manutenção, taxas de plataforma, impostos e períodos sem ocupação.", [("Custos fixos", "Condomínio, IPTU, seguros, internet, equipe e contratos de manutenção continuam mesmo sem reservas."), ("Custos variáveis", "Limpeza, lavanderia, energia, água, gás, amenities e comissões crescem conforme o uso."), ("Reserva para manutenção", "Móveis, equipamentos e acabamentos sofrem desgaste e exigem provisão para reposição."), ("Resultado líquido", "Compare receita recebida com todas as despesas e o custo de oportunidade do imóvel e do capital.")]),
    page("experiencia-hospede-alto-padrao", "Experiência do hóspede em imóveis de alto padrão", "Princípios práticos para melhorar a experiência do hóspede antes, durante e depois de uma estadia.", "Em imóveis de alto padrão, a experiência do hóspede começa antes do check-in. Expectativas corretas, instruções simples, limpeza consistente, manutenção funcional e suporte acessível pesam tanto quanto arquitetura, decoração ou localização.", [("Antes da chegada", "Confirme composição do grupo, acesso, horários, regras, serviços e necessidades relevantes."), ("Primeira impressão", "Limpeza, climatização, iluminação, enxoval e funcionamento dos equipamentos devem ser verificados."), ("Durante a estadia", "O suporte deve ser claro, proporcional e respeitar a privacidade do hóspede."), ("Depois do check-out", "Vistoria, registro de ocorrências e análise de feedback fecham o ciclo de melhoria.")]),
    page("negociacao-imobiliaria-alto-padrao", "Negociação imobiliária de alto padrão", "Como organizar preço, condições, diligência e risco em uma negociação imobiliária de alto padrão.", "Negociações imobiliárias de alto padrão envolvem valores relevantes, múltiplos assessores e condições que podem alterar substancialmente o negócio. Uma proposta forte precisa equilibrar preço, segurança jurídica, financiamento, prazos e alternativas.", [("Preparação", "Defina limite financeiro, prioridades, concessões possíveis e pontos que exigem validação."), ("Proposta completa", "Preço deve vir acompanhado de sinal, prazos, condições, documentos e consequências do inadimplemento."), ("Diligência", "Pagamentos relevantes devem acompanhar a verificação documental e a capacidade de cumprir condições."), ("Alternativas", "Manter opções comparáveis reduz pressão emocional e melhora disciplina na tomada de decisão.")]),
    page("presenca-digital-empresario-imobiliario", "Presença digital para empresário imobiliário", "Como sites próprios, conteúdo e identidade consistente fortalecem autoridade no mercado imobiliário.", "Uma presença digital sólida ajuda empresários do setor imobiliário a controlar informações, demonstrar critérios de atuação e facilitar contato. O valor está na consistência entre identidade, conteúdo útil, fontes verificáveis e atualização contínua.", [("Site oficial", "Um domínio próprio funciona como referência central para biografia, projetos, artigos e contato."), ("Conteúdo útil", "Guias que respondem dúvidas reais constroem autoridade melhor do que páginas repetitivas ou promocionais."), ("Consistência", "Nome, descrições, imagens e links devem permanecer coerentes entre os canais oficiais."), ("Medição", "Search Console e analytics ajudam a priorizar melhorias por consultas, páginas, cliques e conversões.")]),
]

STYLE = ":root{--ink:#18202a;--muted:#5c6570;--soft:#f4f1eb;--accent:#9a6a33;--line:#ded8cf}*{box-sizing:border-box}body{margin:0;font-family:Inter,system-ui,sans-serif;color:var(--ink);line-height:1.65}a{color:inherit}.wrap{max-width:1080px;margin:auto;padding:0 24px}.top,.footer{border-bottom:1px solid var(--line)}.nav{min-height:76px;display:flex;align-items:center;justify-content:space-between;gap:24px}.brand{font-weight:800;text-decoration:none}.links{display:flex;gap:18px;flex-wrap:wrap}.links a{text-decoration:none;color:var(--muted)}.crumbs{padding:18px 0;font-size:.9rem;color:var(--muted)}.hero{padding:72px 0;background:linear-gradient(135deg,#f7f4ef,#fff)}h1{font:700 clamp(2.4rem,6vw,4.6rem)/1.04 Georgia,serif;margin:.2em 0}.lead{max-width:820px;font-size:1.16rem;color:var(--muted)}.content{padding:64px 0}.grid{display:grid;grid-template-columns:repeat(2,1fr);gap:22px}.card{border:1px solid var(--line);border-radius:18px;padding:26px}.card h2{margin-top:0}.cta{margin-top:40px;background:var(--ink);color:#fff;border-radius:20px;padding:30px}.cta a{display:inline-block;margin:8px 12px 0 0;background:#fff;color:var(--ink);padding:11px 17px;border-radius:999px;text-decoration:none;font-weight:700}.footer{border-top:1px solid var(--line);padding:36px 0;color:var(--muted)}@media(max-width:760px){.nav{align-items:flex-start;flex-direction:column;padding:18px 0}.grid{grid-template-columns:1fr}}"


def render(item):
    url = f"{BASE}/{item['slug']}/"
    schemas = [{"@context": "https://schema.org", "@type": "Article", "headline": item["h1"], "description": item["description"], "url": url, "inLanguage": "pt-BR", "dateModified": TODAY, "author": {"@type": "Person", "name": "Rodrigo Cantinho Maldonado", "url": BASE}}, {"@context": "https://schema.org", "@type": "BreadcrumbList", "itemListElement": [{"@type": "ListItem", "position": 1, "name": "Início", "item": BASE + "/"}, {"@type": "ListItem", "position": 2, "name": item["h1"], "item": url}]}]
    cards = "".join(f"<article class='card'><h2>{html.escape(title)}</h2><p>{html.escape(body)}</p></article>" for title, body in item["sections"])
    jsonld = "".join(f"<script type='application/ld+json'>{json.dumps(schema, ensure_ascii=False)}</script>" for schema in schemas)
    return f"""<!doctype html><html lang='pt-BR'><head><meta charset='utf-8'><meta name='viewport' content='width=device-width,initial-scale=1'><title>{html.escape(item['title'])}</title><meta name='description' content='{html.escape(item['description'], quote=True)}'><meta name='robots' content='index,follow,max-image-preview:large'><link rel='canonical' href='{url}'><meta property='og:type' content='article'><meta property='og:locale' content='pt_BR'><meta property='og:title' content='{html.escape(item['title'], quote=True)}'><meta property='og:description' content='{html.escape(item['description'], quote=True)}'><meta property='og:url' content='{url}'><meta name='twitter:card' content='summary_large_image'><style>{STYLE}</style>{jsonld}</head><body><header class='top'><div class='wrap nav'><a class='brand' href='/'>Rodrigo Cantinho Maldonado</a><nav class='links'><a href='/sobre/'>Sobre</a><a href='/portfolio-de-hospedagens/'>Hospedagens</a><a href='/projetos/'>Projetos</a><a href='/artigos/'>Artigos</a><a href='/contato/'>Contato</a></nav></div></header><main><div class='wrap crumbs'><a href='/'>Início</a> › {html.escape(item['h1'])}</div><section class='hero'><div class='wrap'><h1>{html.escape(item['h1'])}</h1><p class='lead'>{html.escape(item['intro'])}</p></div></section><section class='content'><div class='wrap'><div class='grid'>{cards}</div><div class='cta'><h2>Continue explorando</h2><p>Veja outros conteúdos e informações oficiais de Rodrigo Cantinho Maldonado.</p><a href='/artigos/'>Ler artigos</a><a href='/projetos/'>Conhecer projetos</a><a href='/contato/'>Entrar em contato</a></div></div></section></main><footer class='footer'><div class='wrap'>© {date.today().year} Rodrigo Cantinho Maldonado · Site oficial</div></footer></body></html>"""


def sitemap_entry(item):
    return f"  <url><loc>{BASE}/{item['slug']}/</loc><lastmod>{TODAY}</lastmod><changefreq>monthly</changefreq><priority>0.7</priority></url>"


def generate(root=ROOT):
    for item in PAGES:
        folder = root / item["slug"]
        folder.mkdir(parents=True, exist_ok=True)
        (folder / "index.html").write_text(render(item), encoding="utf-8")
    sitemap = root / "sitemap.xml"
    if sitemap.exists():
        xml = sitemap.read_text(encoding="utf-8")
        additions = [sitemap_entry(item) for item in PAGES if f"{BASE}/{item['slug']}/" not in xml]
        if additions:
            sitemap.write_text(xml.replace("</urlset>", "\n".join(additions) + "\n</urlset>"), encoding="utf-8")
    home = root / "index.html"
    marker = "<!-- authority-phase-3 -->"
    if home.exists():
        source = home.read_text(encoding="utf-8")
        if marker not in source:
            hub = marker + "<section style='padding:56px 24px'><div style='max-width:1080px;margin:auto'><h2>Guias de imóveis, negócios e hospitalidade</h2><p>Conteúdo prático de Rodrigo Cantinho Maldonado sobre avaliação, negociação, venda, operação e presença digital.</p><p><a href='/como-avaliar-imovel-alto-padrao-rio/'>Avaliar imóveis</a> · <a href='/comprar-cobertura-ipanema/'>Comprar cobertura</a> · <a href='/gestao-airbnb-alto-padrao/'>Gestão de Airbnb</a> · <a href='/rodrigo-cantinho-maldonado-empresario/'>Perfil empresarial</a></p></div></section>"
            source = re.sub(r"</main>", hub + "</main>", source, count=1, flags=re.I)
            home.write_text(source, encoding="utf-8")


if __name__ == "__main__":
    generate()
    print(f"Generated {len(PAGES)} Phase 3 authority pages")
